# Generated by Django 2.2.19 on 2021-07-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0057_auto_20210525_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foresttask',
            name='total_file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
