# Generated by Django 2.2.24 on 2021-12-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0062_forest_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='jasmine_gyration_radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summarystatisticdaily',
            name='jasmine_significant_location_entropy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
