# Generated by Django 2.2.19 on 2021-08-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0062_participantmessage_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantmessage',
            name='message',
            field=models.CharField(max_length=3900),
        ),
    ]
