# Generated by Django 2.2.19 on 2021-08-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0063_participantfcmhistory_failure_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantmessage',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
