# Generated by Django 2.2.25 on 2022-02-14 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0065_auto_20220119_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelineuploadtags',
            name='pipeline_upload',
        ),
        migrations.DeleteModel(
            name='PipelineUpload',
        ),
        migrations.DeleteModel(
            name='PipelineUploadTags',
        ),
    ]
