# Generated by Django 2.2.25 on 2022-01-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0065_auto_20220119_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
