# Generated by Django 2.2.25 on 2022-02-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0066_remove_researcher_is_batch_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelineuploadtags',
            name='pipeline_upload',
        ),
        migrations.DeleteModel(
            name='PipelineUpload',
        ),
        migrations.DeleteModel(
            name='PipelineUploadTags',
        ),
    ]
