# Generated by Django 2.2.25 on 2022-02-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0066_remove_researcher_is_batch_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
